version: "3"

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    depends_on:
      - wordpress
      - mariadb
    ports: 
      - "443:443"
    volumes: 
      - wordpress:/var/www/wordpress
    networks: 
      - inception
    env_file: .env
    restart: always
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    depends_on: 
      - mariadb
    volumes: 
      - wordpress:/var/www/wordpress
    networks: 
      - inception
    env_file: .env
    restart: always
    expose: 
      - '9000'
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes: 
      - mariadb:/var/lib/mysql
    networks: 
      - inception
    env_file: .env
    restart: always
    expose: 
      - '3306'

volumes:
  wordpress:
    name: wordpress
    driver: local
  mariadb:
    name: mariadb
    driver: local

networks:
  inception:
    name: inception
    driver: bridge
